version: '3.6'
services:
  db:
    image: mysql:5.7.36
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: kerjapraktiklptsi
    volumes:
    - "./database:/var/lib/mysql"
    ports:
    - "9083:3306"
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 9082:80
    environment:
      MYSQL_ROOT_PASSWORD: kerjapraktiklptsi
      PMA_USER: root
      PMA_PASSWORD: kerjapraktiklptsi
  osticket:
    depends_on:
    - db
    image: dockerize_osticket:v1
    volumes:
    - "./osticket:/var/www/html"
    ports:
    - 9080:80